# Load all OpalVite concerns (v1)
require 'opal_vite/concerns/v1/js_proxy_ex'
require 'opal_vite/concerns/v1/dom_helpers'
require 'opal_vite/concerns/v1/toastable'
require 'opal_vite/concerns/v1/storable'
require 'opal_vite/concerns/v1/stimulus_helpers'
require 'opal_vite/concerns/v1/vue_helpers'
require 'opal_vite/concerns/v1/react_helpers'
require 'opal_vite/concerns/v1/uri_helpers'
require 'opal_vite/concerns/v1/base64_helpers'
require 'opal_vite/concerns/v1/debug_helpers'
