# frozen_string_literal: true

source 'https://rubygems.org'

gem 'opal', '~> 1.8'
gem 'opal-vite', path: '../../gems/opal-vite'
gem 'opal_stimulus'

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'capybara-cuprite'
end
