source 'https://rubygems.org'

gem 'opal', '~> 1.8'
gem 'opal-vite', path: '../../gems/opal-vite'
gem 'snabberb', '~> 1.5'

# E2E Testing
group :test do
  gem 'rspec', '~> 3.12'
  gem 'capybara', '~> 3.39'
  gem 'cuprite', '~> 0.15'
end
