source "https://rubygems.org"

# Rails (without ActiveRecord for this demo)
gem "rails", "~> 8.1.0"

# Server
gem "puma", "~> 8.0", ">= 8.0.2"

# Vite integration
gem "vite_rails", "~> 3.0"

# Opal
gem "opal", "~> 1.8"

# Opal-Vite integration (local paths for development/build)
gem "opal-vite", path: "../../gems/opal-vite"
gem "opal-vite-rails", path: "../../gems/opal-vite-rails"
