source 'https://rubygems.org'

gem 'opal', '~> 1.8'
gem 'opal_stimulus', '~> 0.1'
gem 'opal-vite', path: '../../gems/opal-vite'

group :test do
  gem 'rspec', '~> 3.12'
  gem 'capybara', '~> 3.40'
  gem 'cuprite', '~> 0.15'
end
